### PR TITLE
more fixes. and removed the coloring things because it looks very broken with russian

### PR DESCRIPTION
**Pull request by mMONTAGEe**

### CODE REVIEW

**Comment by mMONTAGEe** [comment]
ik ik. seems kinda annoying by making so much fixes lol.

**Comment by mMONTAGEe** [comment]
Ill close this until any plans in future

**Comment by mMONTAGEe** [comment]
ROM. Atleast tell rykllan to check before accepting the pull request

**Comment by ROMVoid95** [comment]
If your going to make a translation, ensure the translation is correct.

**Comment by mMONTAGEe** [comment]
Thats the thing i dont trust myself. i check it ofc but when i ask someone who know better than me. they reveal mistakes.

**Pull request merged**
